### ISSUE TITLE
Learning tools for the project

### ISSUE THREAD

**Issue by zipirovich** [Coldflyer/Google-Scholar-Breadcrumbs-Builder#6]
Each team member may be unfamiliar, to different extents, with the various tools and environments that we will be using for the project:

(*) GitHub
(*) ZenHub
(*) Python language and IDE
(*) Python libraries
(*) AWS

For the first Sprint, everybody needs to start familiarizing themselves with these tools.

**Comment by dasamuels** [comment]
How will we go about measuring/determining when this task is complete?

**Comment by dasamuels** [comment]
If you haven't checked it out, LinkedIn Learning, which we all have access to, has a large number of courses on Python and its libraries, AWS, and Git/GitHub....nothing on ZenHub.
